### ISSUE TITLE
White Appears Below the Footer When in Dark Mode on Smartphones

### ISSUE THREAD

**Issue by tedmagaoay** [zwbetz-gh/cupper-hugo-theme#77]
## Describe the bug
White appears below the footer when in dark mode on smartphones with little or no content pages. Especially when the navTitleText is used instead of the default SVG logo. Everything seems to go up leaving that white space behind.

## To Reproduce
1. Use the navTitleText instead of an SVG.
2. Open a smartphone browser.
2. Go to a page with little or zero content.
3. Turn the dark theme on.

## Expected behavior
Dark mode all the way down, even if the page has just a little content or nothing at all.

## Screenshots

Here there is that white space below the footer.

![has](https://user-images.githubusercontent.com/33870216/190913454-68ea87fa-c14f-45de-aab3-2808a060b2ea.png)

Vs

Here everything is fine.

![has-not](https://user-images.githubusercontent.com/33870216/190914062-fe076f69-acfb-4720-af94-a0aa701644dc.png)

## Smartphone
 - Device: Xiaomi Redmi 9T
 - OS: Android 11
 - Browser: Chrome
 - Version: 105.0.5195.136

**Comment by zwbetz-gh** [comment]
Interesting.

Have you messed with the default CSS? Because the [`main` element should have a `min-height` of `100vh`](https://github.com/zwbetz-gh/cupper-hugo-theme/blob/87e1a8608f44d46f6cc34fc54a4ddadbd2999433/assets/css/template-styles.css#L553), which would force the page to span the full height of the viewport, regardless if there was not enough content on the page.

Now, this could be a bug with your particular mobile device browser.

Also, you didn't mention any scrolling behavior. But if that's your issue, the "overscroll" that happens on both mobile and desktop browsers is normal. Regardless, I've pushed a change to disable this overscroll behavior. See https://github.com/zwbetz-gh/cupper-hugo-theme/commit/be6536778d36eaa223cf492d18af3d4dd9163104

**Comment by tedmagaoay** [comment]
Thank you for your reply and time.

I'm sorry I don't have any CSS knowledge.

I've tried the latest commit and it still persists. 

![aaa](https://user-images.githubusercontent.com/33870216/191194503-104a99c2-6a71-41ca-af4c-ebb12b7229ef.png)

**Comment by zwbetz-gh** [comment]
Ahh, I see now. Okay, I can reproduce this 🙂 

## Before

<img width="1727" alt="Screen Shot 2022-09-20 at 10 27 06 AM" src="https://user-images.githubusercontent.com/37317628/191300180-574db3d8-b2e9-4541-a960-e4761ac3cdee.png">

## After

<img width="1712" alt="Screen Shot 2022-09-20 at 10 27 50 AM" src="https://user-images.githubusercontent.com/37317628/191300211-e0bfc48b-9dbe-4b97-ba4b-6a458e8cea16.png">

## Explanation

The issue is that the `min-height` of the `main` element is being changed to `auto` by a media query on small (mobile) view ports. I've commented it out and done some smoke testing. It seems okay for now. I'll push that change shortly.

**Comment by tedmagaoay** [comment]
It's okay now.

Thank you so much sir.

Have a great day.

**Comment by zwbetz-gh** [comment]
Very nice
